### ISSUE TITLE
Create a snapshot of at least some of the data we need to display - HTTPS

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#10]

**Comment by gbinal** [comment]
Initial thoughts on fields include: 
* [ ] Domain name
* [ ] Agency/Office that owns it
* [ ] Live?
* [ ] Redirect?
* [ ] Participates in DAP?
* [ ] Has HTTPS enabled?
* [ ] Has HTTPS enforced?
* [ ] HSTS policy

**Comment by gbinal** [comment]
What more granular fields could we readily include to reflect the health of the HTTPS implementation?  

cc @konklone

**Comment by konklone** [comment]
Going to reboot this issue in a different form.
