### ISSUE TITLE
Create a snapshot of at least some of the data we need to display - 18F 

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#11]

**Comment by gbinal** [comment]
v0.1 could be:  

* [ ] Domain name
* [ ] Agency/Office that owns it
* [ ] Live?
* [ ] Redirect?
* [ ] Participates in DAP?

**Comment by gbinal** [comment]
I'd love some way of trying to convey thoroughness or health of application.  

Ideas include: 
* Number of pages from domain that have reported data in last 12 months 
* Number of subdomains that have reported data in last 12 months

**Comment by konklone** [comment]
Going to reboot this issue in a different form.
