### ISSUE TITLE
Create a simple-as-necessary front-end

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#13]
...that displays this snapshotted data, with whatever “under construction” caveats are necessary.

**Comment by juliaelman** [comment]
Just had a discussion with @jtexnl and @vzvenyach about the simple front end for Sprint 1. We're moving forward with creating a basic table using the following jQuery tool, which is something that @vzvenyach has used before: https://www.datatables.net/

**Comment by konklone** [comment]
This is done.
