### ISSUE TITLE
Initial ATO

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#17]
- [x] Get delegated authority from OGP to use 18F's ATO process.
- [x] Prepare template ATO for 18F DevOps.
- [x] Have something up there besides the word "PULSE".
- [x] Meet at scheduled time with DevOps to complete process and obtain the ATO.

**Comment by konklone** [comment]
Updated this ticket with specific tasks.

**Comment by konklone** [comment]
Updated the checkboxes above -- most of this is done. The ATO process is scheduled for tomorrow.

**Comment by konklone** [comment]
ATO process was performed for this site and for https.cio.gov, more videos for Kunin Academy were shot. Now just looking for signatures.

**Comment by konklone** [comment]
This is signed.
