### ISSUE TITLE
Create a proper (and evolving) design/UX and information architecture

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#20]

**Comment by konklone** [comment]
This is pretty broad as written. @juliaelman Are you up for creating some specific tickets for Sprint 1 or 2 on how you'd like to approach this?

**Comment by juliaelman** [comment]
@konklone absolutely! On it.

**Comment by juliaelman** [comment]
@konklone I actually already started here >> https://github.com/18F/dotgov-dashboard/issues/15 Created a check list and am basing Sprint 1 tasks off of this ATM. I see this as evolving/changing within the agile process and as we figure out design solutions.
