### ISSUE TITLE
Create Documentation for Maintenance

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#22]

**Comment by konklone** [comment]
I think this mostly amounts to: have a good README. I'm comfortable removing this as a ticket, and re-opening specific tickets if things are identified as we go.

We should make sure our README always documents the current state of getting the project up and running.

**Comment by juliaelman** [comment]
@konklone +1 I think it would be good to put the Milestones or Sprint and specific goals there (eventually).
