### ISSUE TITLE
Brainstorm: Future Dashboard Possibilities

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#29]
Such as:  
* More HTTPS detail, e.g. SHA-1, forward secrecy
* Does the site require “www”? Does it require not using “www”?
* Load time (server-side)
* Mobile friendliness
* Mixed content detection (linking to insecure resources)
* Use of third party services
* 508 compliance (poss. with http://pa11y.org/) 

Add more ideas below.

**Comment by gbinal** [comment]
A good article, re: [mobile-friendliness](http://www.nextgov.com/mobile/2015/04/here-are-agency-websites-google-doesnt-think-are-mobile-friendly/110812/?oref=ng-relatedstories)

**Comment by konklone** [comment]
Same as in https://github.com/18F/dotgov-dashboard/issues/28#issuecomment-95957718, I'd like to direct stuff like this into docs or other discussion places, and keep the ticket tracker focused on action items for development.

**Comment by gbinal** [comment]
Sure thing - Any preference on where it is?  Perhaps a markdown file in /documents?  I'd rather not spin up the wiki.

**Comment by gbinal** [comment]
I'm going to reopen this until we can post a spot that serves in its lieu then am totally cool with closing again.

**Comment by konklone** [comment]
@gbinal How about a section in the README?

**Comment by gbinal** [comment]
Sure thing - I've spun up https://github.com/18F/dotgov-dashboard#ideas-for-later-versions and will now close this and the other related issues.
