### ISSUE TITLE
phase out master branch?  

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#31]
If we plan to heavily use the `gh-pages` branch, anyone have a problem with me porting over the material from `master` to `gh-pages` and killing the `master` branch?  

[Note: I'd do this after the `basic-frontend` branch was merged.]

**Comment by juliaelman** [comment]
:+1: go for it!

**Comment by juliaelman** [comment]
Re-thinking this and wondering if we really should remove the `master` branch if we are pushing to Cloud Foundry?  Will we be deploying the `gh-pages` branch? Seems like double duty to me to have them hosted on both platforms.

Maybe we could keep `master` as our production branch and use the `gh-pages` branch for staging? Still not entirely convinced we need both.

**Comment by juliaelman** [comment]
Re-opening, as we still need to determine whether or not this is something we want/need to do.

**Comment by juliaelman** [comment]
Team decided to move forward with no gh-pages branch and sticking with Cloud Foundry only. Thanks for the feedback all!
