### ISSUE TITLE
Compare official .gov fields indicating whether site is up to our list

### ISSUE THREAD

**Issue by konklone** [18F/dotgov-dashboard#34]
The .gov registrar has a field in one of their spreadsheets that tracks whether the site is up or down. We should compare this against our own dataset, based on [`site-inspector`](https://github.com/benbalter/site-inspector-ruby), to see if there are many major discrepancies.

cc @jtexnl - I think this would be a good one for you. (I can formally "assign" issues once you've joined the org.)

**Comment by jtexnl** [comment]
Submitted this pull request: 
https://github.com/18F/dotgov-dashboard/pull/63
The analysis found quite a few discrepancies. Spot checking seems to indicate that either the site inspector is more accurate, or there were a lot of changes between the March snapshot and the late April scan.
