### ISSUE TITLE
Create one-time snapshot of .gov DAP participation

### ISSUE THREAD

**Issue by konklone** [18F/dotgov-dashboard#53]
I generated [`analytics.csv`](https://github.com/18F/dotgov-dashboard/blob/master/data/analytics.csv) by matching the federal (exec+leg+jud) .gov domain list to the [3800 sites the DAP says participate](https://analytics.usa.gov/data/sites.csv).

This is almost good enough, but the [~300 exec branch domains DAP says participate](https://www.digitalgov.gov/files/2012/10/DAP-Domains-and-Agencies-3-2015-Sheet1.csv) doesn't line up with this -- there are more domains there (and that's only exec branch).

Let's figure out why that is, so we can finalize the snapshot.

**Comment by konklone** [comment]
The simplest reason may be that the .gov domains are being compared to only second-level domains. So for example, `embassy.gov` as a root domain doesn't appear in the DAP, but many of its subdomains do. So "embassy.gov" may participate, even if "https://embassy.gov" does not.

**Comment by gbinal** [comment]
I think that's it but will noodle on it, some.

**Comment by konklone** [comment]
@gbinal This seemed implied to be part of sprint 2 to me -- just assigned you for it.

**Comment by konklone** [comment]
I don't see the same discrepancy I once did, so we're good on this.
