### ISSUE TITLE
Arrive at consensus on wireframes for the phase 1 

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#56]
The steps for this are:  
* [ ] [Get Feedback on wireframes v2](https://github.com/18F/dotgov-dashboard/issues/55)
* [ ] [Design Wireframes v3](https://github.com/18F/dotgov-dashboard/issues/58)
* [ ] [Gain external feedback on wireframes v3](https://github.com/18F/dotgov-dashboard/issues/59)
* [ ] [Design wireframes v4](https://github.com/18F/dotgov-dashboard/issues/61)

**Comment by konklone** [comment]
Since these are all individual tickets (which is preferred :+1:) this can be closed, I think.
