### ISSUE TITLE
Prepare wireframes for initial implementation

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#58]
Building on #55

**Comment by konklone** [comment]
Updated title. I'd describe this ticket as:

- [ ] Revising wireframes based on sprint planning discussion,and followup discussion. (2 column layout, moving agencies to sidebar.)
- [ ] Publishing those wireframes in this repository somewhere.

**Comment by juliaelman** [comment]
Closing this, as #75, #76, #77 and #78 complete the final task.
