### ISSUE TITLE
Revise wireframes based on external feedback before initial implementation

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#59]
Depends on #58.

**Comment by konklone** [comment]
Updated title and description. This ticket follows #58, and should be a quick round of wireframe circulation amongst the team, along with anyone else we'd like to ping to glance at the public wireframe  files we added to the repo.

**Comment by juliaelman** [comment]
@gbinal we're good to go on this and folks can comment/leave feedback on the following issues: #75, #76, #77, #78.
