### ISSUE TITLE
Decide which "federal agencies" to display

### ISSUE THREAD

**Issue by jtexnl** [18F/dotgov-dashboard#64]
Currently, there are 126 agencies identified in the data as "federal agencies" in charge of websites. Several of them are agencies in charge of just one domain, others may only have one or two, and many are not what one would traditionally think of as federal agencies (Amtrak, for example). Single-site agencies won't make compelling data visualizations (everything will be 100% in either direction), so I would propose that we remove them from visualizations, while still making their data available in the table.

**Comment by juliaelman** [comment]
@jtexnl thanks for posting this! How many agencies would that remove?

**Comment by jtexnl** [comment]
Looks like about 54 would drop out, so we'd be left with 72

**Comment by gbinal** [comment]
I'm on the fence on this one.  Another option might be to bundle them as 'Other Agencies' or 'Single Domain Agencies'.

**Comment by konklone** [comment]
It might be easier to just forgo grouping by agency this sprint and, within the confines of our much-improved layout, flatten it to just listing all ~1,300 domains and filtering on those. That would likely forgo the donut visualization, since each landing page would only be about a single domain, but it would simplify things.

**Comment by juliaelman** [comment]
I agree with @konklone and vote that we move forward with domains only. Regardless of the decisions made in the previous wireframes, it would be good to get confirmation directly from a CIO interview that they would actually WANT to see their web properties at a agency level first (see #65).

**Comment by gbinal** [comment]
Works for me, esp. if it's simpler.

**Comment by konklone** [comment]
Okay - then this will take shape in the next version of wireframes.

**Comment by juliaelman** [comment]
@gbinal thinking of a very simple display! :+1: Thanks all!

**Comment by jtexnl** [comment]
After thinking this issue over more, I have to disagree with the move away from aggregating data to an agency level. First of all, having some sort of visualization is important, and has been specifically mentioned by Dominic and some other OGP people. For CIO users, being able to quickly see how their agency's web presence as a whole is doing will save time and capture the user's attention better than a table alone would. There are a lot of other fringe use cases (OMB, media, etc) that would beenfit more from a visualization that paints a broader story. A table is certainly necessary, but I think a visualization adds a lot as well.

**Comment by gbinal** [comment]
One compromise - the simpler display of all and then a 2nd page that shows: 
1) a combined donut chart of all 
2) donut charts for the CFO-Act Agencies

That said, there's value in adding such a 2nd page but also complexity and effort.  At this point, @konklone and @juliaelman are on a push to have something for Wednesday - let's see how that looks.

**Comment by juliaelman** [comment]
@jtexnl @gbinal all good points and thank you for posting your comments. We'll take this all into consideration for this next round of high fidelity wireframes.
