### ISSUE TITLE
Change placeholder text on live pulse.18F.gov page

### ISSUE THREAD

**Issue by jtexnl** [18F/dotgov-dashboard#66]
Could we make the placeholder text at the top of the pulse page a little bit more official sounding in case someone who comes across the page is not technical? There has been some concern that the pre-alpha language might be confusing to non-technical folks. I know we're not publicizing anything yet, so no outside parties should get onto the site in theory, but some folks at OGP are uneasy about the language as it stands nonetheless. I'd suggest "This website is in a very early stage of development. No information or content found here should be considered definitive."

Thanks, and sorry for the nitpickiness of this issue.

**Comment by konklone** [comment]
@jtexnl How about a pull request? :smile:

**Comment by jtexnl** [comment]
Done; it's on the production branch. Is that the right place?

**Comment by konklone** [comment]
Not quite -- I was suggesting a pull request that made the changes to the content you'd like to see. The workflow should be:

* Make a new branch, branched off of `staging`.
* Make the edits, and push to this repository.
* Create a pull request that asks to merge in the changes from your new branch to the `staging` branch.
* Someone reviews that PR and then merges it.
* After confirming that staging looks/works as expected, you or someone else opens a PR from `staging` to `production`.
* Someone merges that production PR and the work is done.

**Comment by konklone** [comment]
(I meant the `master` branch, not `staging` -- updated comment.)
