### ISSUE TITLE
Domain eligibility for DAP

### ISSUE THREAD

**Issue by konklone** [18F/dotgov-dashboard#71]
We need to decide which second-level domains (e.g. agency.gov) are eligible to be considered for DAP participation.

@tdlowden @smarina04, do either of you keep any sort of list of domains not considered eligible for DAP? Is there any written articulation of what domains are ineligible (e.g. login portals, IC work, etc.)?

**Comment by smarina04** [comment]
All public-facing, exec branch federal government second-level domains (.gov, .mil) and even exceptions such as .net. .org. and .com are allowed.  Portals are allowed for the public-facing pages only (e.g. home page). The whole idea behind eligibility of gov websites for the purposes of DAP is that the if public can see those pages, then it should be in DAP. We have no written instructions for ineligible domains, but I think that "public-facing" is pretty self-explanatory.

**Comment by konklone** [comment]
That was way more simple than I was expecting. So the way I would translate this into technical attributes are:

* The domain is reachable over HTTP.
* The domain is not a "redirector" to another domain (e.g. `ethics.gov`). It brings the user to a page on its own domain.

@smarina04 Do you see any issue with listing _all_ publicly reachable, non-redirect domains as potentially DAP-eligible? Are there any other one-off's or criteria we should be considering?

**Comment by smarina04** [comment]
No issue as long as they are Executive Branch and publicly reachable second-level domains (and not redirects).

**Comment by konklone** [comment]
Gotcha, then there are three criteria:

* The domain is reachable over HTTP.
* The domain is not a "redirector" to another domain (e.g. `ethics.gov`). It brings the user to a page on its own domain.
* The domain is administered by the federal government's executive branch.

We'll proceed with those in mind. Thank you, and please comment/re-open if you can think of anything else.
