### ISSUE TITLE
Kick off accessibility review

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#73]
We should initiate the accessibility review of our work, once we have our wireframes implemented in HTML and up at the production site.

**Comment by nickbristow** [comment]
@juliaelman asked me to take a look through local tunnel. Here are some things I noticed. 

- [ ] Unique Page titles (about page, analytics)
- [ ] Associate "Show __ Entries" label with select box
- [ ] For tables (https, analytics) add scope to column headers and row headers (first element)
- [ ] Add visual focus when using keyboard to tabs (about, analytics, HTTPS)
- [ ] Add skip nav link
- [ ] Add aria to pagination links on tables

**Comment by juliaelman** [comment]
Awesome - thanks you @nickbristow for posting these here! I am going to make a separate issue for these tasks and push into the Sprint 3 milestone.
