### ISSUE TITLE
Plan User Experience Feedback for Sprint 3

### ISSUE THREAD

**Issue by gbinal** [18F/dotgov-dashboard#74]

**Comment by konklone** [comment]
@gbinal My original request was to make the *planning* part of the user research begin in Sprint 2, so that we could execute it in the early part of Sprint 3 with enough time to respond to the results.

**Comment by gbinal** [comment]
Ah, yes.  Sorry, we're on the same page.  That's what I had in mind, too.

**Comment by juliaelman** [comment]
Would it be possible to write down any specific tasks and/or objectives that you all think we should do in order to accomplish this issue? As it's stands, it's a bit confusing on exactly what you'd like to accomplish for this in Sprint 2.

**Comment by konklone** [comment]
I understood this as figuring out what and when our usability research session is going to be, and who's going to run it, etc., before sprint 2 is out -- even if the session itself happens in sprint 3.

**Comment by juliaelman** [comment]
Meeting with @leahbannon and writing up a game plan tomorrow (5/14) to share with the team. Stay tuned!
