### ISSUE TITLE
Homepage front end implementation

### ISSUE THREAD

**Issue by juliaelman** [18F/dotgov-dashboard#75]
Below is the PNG layout for the Pulse homepage. Please note that the numbers are not accurate in this sketch are are merely for positioning. Accurate figures will be part of this implementation and are listed as one of the tasks below:

- [x] Create initial stylesheets for overall look/feel for the site (basic level; Bourbon/NEAT)
- [x] Add top navbar with corresponding links to pages
- [x] Check-in with the design team about header/footer usage as seen on other 18F projects (e.g. openFOIA)
- [x] Add suggested header/footers per design direction to Sketch files + code
- [x] Collect aggregate data on the homepage for overall HTTPS and DAP stats
- [x] Add donut chart implementation of the data 

![homepage](https://cloud.githubusercontent.com/assets/955558/7573576/b3b61026-f7f4-11e4-964c-44d9abad511f.png)

**Comment by konklone** [comment]
Work is ongoing in the `homepage` branch. The other wireframe tickets (#76, #77, #78) should not be worked on until this branch is merged in, as it contains most of the initial framing and layout. Sorry to be a blocker! I'll try to get the frame merged in first, before the homepage is fully done and this ticket can be closed, and release the block.

**Comment by juliaelman** [comment]
@konklone I reviewed the PR, made some changes and merged it in. Thanks for knocking out the first three tasks on this issue :+1:

**Comment by juliaelman** [comment]
Overall feedback from the design team was to place the current footer disclaimer at the top of the page, rather than the bottom.

**Comment by konklone** [comment]
:+1:

**Comment by konklone** [comment]
Closed with #90.
