### ISSUE TITLE
About page front end implementation

### ISSUE THREAD

**Issue by juliaelman** [18F/dotgov-dashboard#76]
Below is the PNG layout for the About page. A few things that we discussed today and that also need to get accomplished in partnership with this issue:

- [x] Complete layout implementation in template
- [x] Write copy for Frequently Asked Questions

![about](https://cloud.githubusercontent.com/assets/955558/7573588/c0ba0250-f7f4-11e4-8472-927fe2bd788c.png)

**Comment by juliaelman** [comment]
@konklone opened #86 for styling implementation and assigning this over to you for copy.

**Comment by juliaelman** [comment]
Initial copy has been written, but we still need to think about where to point folks to in order to to get better scores. Moving this into Sprint 3.

**Comment by konklone** [comment]
@juliaelman Since we're tracking the score/implementation concerns in #113, is this good to close?

**Comment by juliaelman** [comment]
@konklone +1 and closed.
