### ISSUE TITLE
Add Jekyll to repo setup and README.md

### ISSUE THREAD

**Issue by juliaelman** [18F/dotgov-dashboard#79]
After coming to a more well defined version of the wireframes, @konklone agreed that moving forward with implementing Jekyll is something that makes the most sense. Here are some of the tasks to accomplish to complete this work:

- [x] Add `Gemfile` to repo (or whatever would work best) to include Jekyll into the setup
- [x] Add any additional installation instructions to `README.md` to guide any new or existing contributors on how to use this new setup

**Comment by juliaelman** [comment]
@konklone adding you as the implementer for this issue, but let me know if you need anything else from me!

**Comment by konklone** [comment]
The infrastructure work was done in #80, and I've since re-configured our Travis, Cloud Foundry, and webhook setups to restore auto-deploy to staging and production. All done!
